### ISSUE TITLE
Bitmap upside-down?

### ISSUE THREAD

**Issue by salmanarif** [HPCE/hpce-2014-cw4#8] opened 2015-02-15 19:02 UTC
Hi,

In the readme, it says that `render_world` will save the world as a bitmap where high temperature cells will be red, and low temperature cells will be blue.

It appears that the rendered bitmap is upside-down. For example, with the following command:
`make_world.exe 100 0.1 | step_world 0.1 100000 | render_world dump.bmp`

The following image is rendered:
![dump](https://cloud.githubusercontent.com/assets/8473947/6204485/26e157ba-b545-11e4-91b0-b64b5c284302.png)

The text output from `step_world` is:
![Text output](https://cloud.githubusercontent.com/assets/8473947/6204484/05ee885c-b545-11e4-9df8-5d0587b96250.png)

**Comment by m8pple** [comment] 2015-02-16 18:27
It's a known (vaguely intentional) issue - it's a legacy design decision that won't get fixed as
it will break existing code. y-flipping co-ordinate transforms when rendering as images are common,
so I'm going to close it as Not A Bug.

But thanks for documenting it.

**Closed as completed by m8pple** 2015-02-16 18:27 UTC
